# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/eduard/programming/VPNSwitcher/select.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerSelector(object):
    def setupUi(self, ServerSelector):
        ServerSelector.setObjectName("ServerSelector")
        ServerSelector.resize(305, 328)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ServerSelector.sizePolicy().hasHeightForWidth())
        ServerSelector.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(ServerSelector)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(ServerSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setAutoFillBackground(False)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout_2.addWidget(self.treeWidget, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.disconnectButton = QtWidgets.QPushButton(ServerSelector)
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout.addWidget(self.disconnectButton)
        self.hideButton = QtWidgets.QPushButton(ServerSelector)
        self.hideButton.setObjectName("hideButton")
        self.horizontalLayout.addWidget(self.hideButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(ServerSelector)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(ServerSelector)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(ServerSelector)
        QtCore.QMetaObject.connectSlotsByName(ServerSelector)

    def retranslateUi(self, ServerSelector):
        _translate = QtCore.QCoreApplication.translate
        ServerSelector.setWindowTitle(_translate("ServerSelector", "Form"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("ServerSelector", "Country"))
        self.treeWidget.headerItem().setText(1, _translate("ServerSelector", "Number"))
        self.treeWidget.headerItem().setText(2, _translate("ServerSelector", "Ping"))
        self.disconnectButton.setText(_translate("ServerSelector", "Disconnect"))
        self.hideButton.setText(_translate("ServerSelector", "Hide"))
        self.pushButton.setText(_translate("ServerSelector", "Connect"))
        self.label.setText(_translate("ServerSelector", "Select a server"))
